### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by karsV48** [badRyuk/GenBot#3]
When I try to run the bot it says: CLIENT_MISSING_INTENTS, how do I fix this

**Comment by badRyuk** [comment]
What node.js version are you running? Try running `node -v` on command prompt or PowerShell.

**Comment by badRyuk** [comment]
Not waiting for more days/months, you need to reply if you want me to help you out honestly. Anyways open a new issue if you want to ask or something. I'm done with this stuff literally every issue here is opened by a completely new account, same for the stars. Probably gonna archive it in a month from now if I see no issues or something like this were the person doesn't respond. Closing the Issue
